name: Continuous Integration

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run typecheck
        run: npm run typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run typecheck
        run: npm run typecheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
